// OPERADORES PARTE 2 

/*
  OPERADORES RELACIONAIS
 * > MAIOR
 * < MENOR
 * >= AMIOR IGUAL
 * <= MENOR IGUAL
 * == IGUAL
 * != DIFERENTE
 * === IDENTIDADE, TESTA TIPO E VALOR
 * ELES RETORNA SÓ (TRUE) E (FALSE)
*/


/*
 * OPERADORES LOGICOS
 * ! NOT -> NÃO -> SE EU PEDIR UMA CANETA E FALAR QUE NÃOPODE SER AZUL, ENTÃO QUALQUER COR SERVE
 *
 *
 * & AND -> E TEM QUE SER UM CANETA AZUL E UMA VERMELHA
 * PARA SER VERDADEIRO, OS DOIS LADOS TEM QUE SER VERDADEIRO. SE TIVER UM FALSO OS DOIS FICAM FALSOS
 *
 *
 *
 * || OR -> OU UMA AZUL OU UMA VERMELHA, PARA DÁ VERDADEIRO SERVE OU UMA O OUTRA. PARA DA TRUE UM DOS LADOS TEM QUE SER VERDADIERO
 *
 *  ? : OPERADOR TERNARIO É COMO SE FOSSE UM IF E ELSE
 *  PARA OPERAÇÃO MENOR 
 *  EX: media>=7.0 ? 'aprovado' : 'reprovado'  
 */

